name: Flutter Firebase CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      #      - name: Run tests
      #        run: flutter test

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        run: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers"